// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwhp23PGTcFPpmA1SeaXKc7An3Y9l3OS8',
    appId: '1:873471726718:web:5e813465f714948247f42f',
    messagingSenderId: '873471726718',
    projectId: 'chatapp-5d856',
    authDomain: 'chatapp-5d856.firebaseapp.com',
    storageBucket: 'chatapp-5d856.firebasestorage.app',
    measurementId: 'G-SFS5LFE0JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESv8eYISN_MqdWIIpf48EZ1IUBUA1Tr4',
    appId: '1:873471726718:android:4f8453eaed992d9347f42f',
    messagingSenderId: '873471726718',
    projectId: 'chatapp-5d856',
    storageBucket: 'chatapp-5d856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUyjO4rchw1qdYXETtfeCdxSAPZYqPT4',
    appId: '1:873471726718:ios:e46e7ce38b43433247f42f',
    messagingSenderId: '873471726718',
    projectId: 'chatapp-5d856',
    storageBucket: 'chatapp-5d856.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUyjO4rchw1qdYXETtfeCdxSAPZYqPT4',
    appId: '1:873471726718:ios:e46e7ce38b43433247f42f',
    messagingSenderId: '873471726718',
    projectId: 'chatapp-5d856',
    storageBucket: 'chatapp-5d856.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwhp23PGTcFPpmA1SeaXKc7An3Y9l3OS8',
    appId: '1:873471726718:web:5a3dfec9409dd0de47f42f',
    messagingSenderId: '873471726718',
    projectId: 'chatapp-5d856',
    authDomain: 'chatapp-5d856.firebaseapp.com',
    storageBucket: 'chatapp-5d856.firebasestorage.app',
    measurementId: 'G-7CYFS9X880',
  );
}
